services:
    _defaults:
        autowire: true
        autoconfigure: true

    Glavnivc\UserBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Security/Event,Kernel.php}'

    user_bundle.user.provider.entity:
        alias: Glavnivc\UserBundle\Security\User\UserProvider

    user_bundle.authenticator.login_form:
        alias: Glavnivc\UserBundle\Security\Authenticator\LoginFormAuthenticator

    user_bundle.handler.access_denied:
        alias: Glavnivc\UserBundle\Security\AccessDeniedHandler

    Glavnivc\UserBundle\Security\User\UserProvider:
        class: Glavnivc\UserBundle\Security\User\UserProvider
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $classOrAlias: Glavnivc\UserBundle\Entity\User
            $property: username

    Glavnivc\UserBundle\Security\Credentials\LocalCheckCredentialsService:
        class: Glavnivc\UserBundle\Security\Credentials\LocalCheckCredentialsService
        arguments:
            $config: []

    Glavnivc\UserBundle\Security\Permission\Provider\LocalPermissionProvider:
        class: Glavnivc\UserBundle\Security\Permission\Provider\LocalPermissionProvider
        arguments:
            $config:
                projectDir: '%kernel.project_dir%'
                permissionsFile: "%env(string:LOCAL_PERMISSIONS_FILE)%"
            $cache: '@cache.app'
            $logger: '@logger'

    Glavnivc\UserBundle\Security\Permission\Service\LocalPermissionService:
        class: Glavnivc\UserBundle\Security\Permission\Service\LocalPermissionService
        arguments:
            $permissionProvider: '@user_bundle.permission.provider.local'
            $checkCredentialsService: '@user_bundle.service.credentials.local'
            $cache: '@cache.app'
            $logger: '@logger'

    user_bundle.permission.service.local:
        alias: Glavnivc\UserBundle\Security\Permission\Service\LocalPermissionService

    user_bundle.permission.provider.local:
        alias: Glavnivc\UserBundle\Security\Permission\Provider\LocalPermissionProvider

    user_bundle.service.credentials.local:
        alias: Glavnivc\UserBundle\Security\Credentials\LocalCheckCredentialsService
