services:
    _defaults:
        autowire: true
        autoconfigure: true

    Glavnivc\UserBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Security/Event,Kernel.php}'
